apiVersion: apps/v1

kind: Deployment

metadata:
  name: my-python-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: my-python-app

  template:
    metadata:
      labels:
        app: my-python-app

    spec:
      containers:
        - name: my-python-app

          image: localhost:5000/my-python-app:latest # Local image name and tag

          ports:
            - containerPort: 80
